[project]
name = "quiz-master"
version = "0.1.0"
description = "An interactive CLI to create home server applications as Helm Charts"
readme = "README.md"
requires-python = "=3.13.2"
dependencies = [
    "questionary>=2.1.0",
    "pyinstaller (>=6.12.0,<7.0.0)",
]
