{{ range .Values.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "[[ chart.name ]].name" $ }}-{{ .name }}
  labels:
    {{- include "[[ chart.name ]].labels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
      name: {{ .name }}
  selector:
    {{- include "[[ chart.name ]].selectorLabels" $ | nindent 4 }}
{{ end }}
