{{ if .Values.configMapEnv }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "<CHARTNAME>.name" $ }}-env
  labels:
    app.kubernetes.io/name: {{ include "<CHARTNAME>.name" $ }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  {{- range $key, $val := $.Values.configMapEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{ end }}