{{ range .Values.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "<CHARTNAME>.fullname" $ }}-{{ .name }}
  labels:
    {{- include "<CHARTNAME>.labels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
      name: {{ .name }}
  selector:
    {{- include "<CHARTNAME>.selectorLabels" $ | nindent 4 }}
{{ end }}
